### ISSUE TITLE
No DLC displayed when game is launched 

### ISSUE THREAD

**Issue by JadedMechanic** [DarkMatterCore/wad2bin#11]
I’m very new to this so I apologise if any of this is common knowledge or if I’ve left anything out that is important for accurate diagnosis

I have followed your guide and I’ve gotten as far as uninstalling and installing the bogus.wad, I get the 1022 error and I’ve ignored it like the guide suggests, however when I run guitar hero 5 off USB loader GX and go to the archive the SD states it has no songs to display

is there more information I can provide for further diagnosis?
And do you have any suggestions on what I can try to get it going?

I appreciate any feedback you can provide, thanks guys

**Comment by DarkMatterCore** [comment]
@JadedMechanic Refer to the readme:

> * Converted DLC data can be encrypted using either a null key (used by older games) or the console-specific PRNG key (used by newer games, and also old games when launched with a cIOS).

And also:

> * **DLCs:** the game must be launched using a cIOS, or its required IOS version must be patched to enable the signing bug on it. This greatly depends on:
>     * **How old the game is:** if it enforces the usage of a null key when launched through the Disc Channel.
>     * **The used launch method:** cIOS enforce the usage of the PRNG key, even on older games.
>     * **Ticket/TMD signature validity:** if it's not valid, or if the ticket wasn't issued for the target console, a patched IOS or a cIOS will always be necessary.
>     * Because of all these reasons, it's difficult to establish a clear procedure that works for every single case. Further trial and error by the user is encouraged.

It's hard to tell what's wrong because some games use a null encryption key for DLCs, while others use the PRNG key from the console they belong to.

**Comment by DarkMatterCore** [comment]
@JadedMechanic I'm closing this issue for the time being. If you can't get the DLCs to work by trial and error (e.g. different cIOS, null / PRNG key, etc.), feel free to reopen this issue.

**Comment by Mordius** [comment]
Hey, I followed this guide like 2 days ago but got the same problem, all of the process worked without issues but the DLC songs weren't showing in game (Guitar Hero Warriors of Rock). After 2 days of troubleshooting I finally got it working

Apparently you have to open the **Wii Shop Channel** at least once (Open the channel, accept the terms and conditions and get to the point where you can search for titles in the shop channel). Once you done that go into GH and try to open the **in-game shop** (It will fail because servers are down), but if you now go to **Options** then **Rock Archive** all the DLC songs you installed will be there
