### ISSUE TITLE
[Feature Request] Reverse the process

### ISSUE THREAD

**Issue by zurgeg** [DarkMatterCore/wad2bin#18]
We have wad2bin, which lets us put WADs from our PCs onto our SD cards in bin form, so why not have bin2wad, which lets us put bins from our SD cards into WAD form?

**Comment by DarkMatterCore** [comment]
[Because I did it almost 10 years ago.](https://github.com/DarkMatterCore/bluedump-mod)

**Comment by DarkMatterCore** [comment]
Honestly, it's better this way because YABDM just grabs the required keydata from the console itself while reading content.bin files, so you could say two birds are killed with one stone.

**Comment by DarkMatterCore** [comment]
@zurgeg I sincerely apologize if my initial answer came off as rude -- I wasn't feeling all too well that day and this is a very personal aspect I'm trying to keep in check.

In any case, the reason why bin2wad isn't a thing is because it'd be cumbersome (e.g. users would also have to manually dump tickets from their consoles), and a conversion tool that runs right on your Wii has already existed for years now.

Being rude wasn't my intention. Sorry.

**Comment by zurgeg** [comment]
> @zurgeg I sincerely apologize if my initial answer came off as rude -- I wasn't feeling all too well that day and this is a very personal aspect I'm trying to keep in check.
> 
> In any case, the reason why bin2wad isn't a thing is because it'd be cumbersome (e.g. users would also have to manually dump tickets from their consoles), and a conversion tool that runs right on your Wii has already existed for years now.
> 
> Being rude was never my intention, and you truly didn't deserve to be treated like that. Sorry.

Ah no, it's fine!
