### ISSUE TITLE
It won't start?

### ISSUE THREAD

**Issue by RyderSchuett** [DarkMatterCore/wad2bin#2]
Whenever I open the .py file, it just opens a black window, that immediately disappears. Same for the .exe file.

**Comment by DarkMatterCore** [comment]
@RyderSchuett Hi there. Nice to meet you.

Have you installed Python on your PC? Without it, the .py script won't be able to run, so you won't have access to the graphical Python frontend.

The program itself (the .exe file) is a command line only utility, which means you can only use it via a command line window. What's you describe is an expected behaviour.
