### ISSUE TITLE
After installing bogus wads I get this error with Wii Mod Lite

### ISSUE THREAD

**Issue by msimplay** [DarkMatterCore/wad2bin#6]
After installing bogus wads I get this error with Wii Mod Lite
![IMAG1237](https://user-images.githubusercontent.com/49412623/106344053-858f9100-62a0-11eb-8e55-c040a0236a1c.jpg)

Error:: Failed to get TMD size. tid = 2814807XXXXXXXX

Then freezes the console and I have to reboot

However I am able to use Wii Mod 3.2 and can use wad manager there

**Comment by DarkMatterCore** [comment]
It's a Wii Mod Lite issue.

Bogus WADs only hold TMD and Ticket data. In regular WAD Managers such as the original one developed by Waninkoko, installing a bogus WAD should only yield a -1022 error, but TMD and Ticket data should be installed anyway.

This won't be fixed in wad2bin because there's nothing to fix.

**Comment by msimplay** [comment]
Thanks for the update I'll report it to them and see what they say
